  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Navbar from "@/components/Navbar";
  import Footer from "@/components/Footer";
  import SessionWrapper from "@/components/SessionWrapper";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata = {
    title: "Get me a Chai - Fund for chai lovers",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }) {
    return (
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-screen flex flex-col">
          <SessionWrapper>
          <Navbar/>
          <div className="min-h-full relative">
            <div className="absolute top-0 z-[-2] h-full w-screen bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] text-white">

            </div>
          {children}
          </div>
          <Footer/> 
          </SessionWrapper>
          </body>
      </html>
    );
  }
